name: Label Feature PRs for Auto-merge

on:
  pull_request:
    types: [opened]
  workflow_run:
    workflows: ["Tests", "Lint"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PLEASE_RELEASE_APP_ID }}
          private-key: ${{ secrets.PLEASE_RELEASE_PRIVATE_KEY }}

      - name: Label PR when tests pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            let prNumber;
            let headSha;

            if (context.eventName === 'pull_request') {
              // Don't auto-label on PR open, wait for tests
              return;
            } else if (context.eventName === 'workflow_run') {
              // Get PR from workflow run
              const workflowRun = context.payload.workflow_run;

              if (workflowRun.conclusion !== 'success') {
                console.log('Workflow did not succeed, skipping');
                return;
              }

              headSha = workflowRun.head_sha;

              // Find PR associated with this commit
              const { data: prs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:${workflowRun.head_branch}`
              });

              if (prs.length === 0) {
                console.log('No open PR found for this workflow run');
                return;
              }

              prNumber = prs[0].number;
            } else {
              return;
            }

            // Check if both Tests and Lint workflows have passed for this PR
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: headSha
            });

            const testsPassed = checkRuns.check_runs.some(run =>
              run.name === 'test' && run.conclusion === 'success'
            );

            const lintPassed = checkRuns.check_runs.some(run =>
              run.name === 'lint' && run.conclusion === 'success'
            );

            if (testsPassed && lintPassed) {
              // Add automerge label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['automerge']
              });

              console.log(`Added automerge label to PR #${prNumber} - all checks passed`);
            } else {
              console.log(`Not all checks passed for PR #${prNumber}. Tests: ${testsPassed}, Lint: ${lintPassed}`);
            }
